"""
app/models/auth_models.py
==================
Auth models (Biometric and invite links).
"""

from app.db.base import Base
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, func
from sqlalchemy.orm import relationship


class InviteLink(Base):
    """
    Child invite link generated by a parent.

    The parent generates this token and shares it with the child's device.
    The child taps the link → app opens → child is auto-logged in with
    a long-lived read token (no password needed on the child's device).

    The token is a signed JWT — it does not need to be stored here for
    verification, but we store it so the parent can revoke it and so we
    can list active links.

    Link format:
        phonicsfriends://join?token=<jwt>
        or (if domain configured):
        https://phonicsfriends.app/join?token=<jwt>
    """

    __tablename__ = "invite_links"

    id = Column(Integer, primary_key=True, index=True)
    parent_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    child_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token = Column(String(512), nullable=False, unique=True)
    # Human-readable label shown in parent dashboard
    label = Column(String(100), nullable=True)
    is_active = Column(Boolean, default=True)
    # How many times the link has been used (for analytics)
    use_count = Column(Integer, default=0)
    # When the token expires (default 7 days, renewable)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), default=func.now())
    last_used_at = Column(DateTime(timezone=True), nullable=True)

    parent = relationship("User", foreign_keys=[parent_id], backref="generated_links")
    child = relationship("User", foreign_keys=[child_id], backref="invite_links")


class BiometricToken(Base):
    """
    Stores a device-specific biometric authentication token for parents.

    When a parent registers, a long-lived biometric_token is issued and
    stored encrypted on the device. When the parent taps the biometric
    button, the device decrypts the token using fingerprint/face, sends
    it to the backend to exchange for a fresh JWT.

    This is separate from the WebAuthn passkey flow — it's simpler and
    works on older devices.
    """

    __tablename__ = "biometric_tokens"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # Hashed token stored here; actual token stored encrypted on device
    token_hash = Column(String(64), nullable=False, unique=True)
    device_id = Column(String(200), nullable=True)  # optional device fingerprint
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=func.now())
    last_used_at = Column(DateTime(timezone=True), nullable=True)

    user = relationship("User", foreign_keys=[user_id], backref="biometric_tokens")
