"""
app/models/parent.py
====================
Parent role models.

A User with role=PARENT owns:
  - One or more child accounts (Users with role=STUDENT)
  - The subscription (pays for the family)
  - Learning goals per child
  - Access to progress analytics and weekly AI reports

Design decisions:
  - ParentChildLink is a separate table (rather than a column on User)
    so one parent can have multiple children. For this version, each
    child belongs to exactly one parent (enforced by the unique
    constraint on child_id below) — co-parenting / multiple parents
    per child is not supported yet and would need a schema change.
  - LearningGoal is per-child, set by the parent.
  - WeeklyReport is generated by AI on Monday mornings and cached.
  - ScreenTimeLog records every session so parents can see
    daily/weekly usage without polling the child's device.
"""

from app.db.base import Base
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import relationship


class ParentChildLink(Base):
    """
    Links a parent User to a child User.
    A parent can have many children; each child belongs to exactly one
    parent (child_id is unique below) for this version.
    """

    __tablename__ = "parent_child_links"

    id = Column(Integer, primary_key=True, index=True)
    parent_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    child_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    is_primary = Column(Boolean, default=True)  # primary parent = the one who pays
    nickname = Column(String(50), nullable=True)  # parent's nickname for this child
    created_at = Column(DateTime, default=func.now())

    parent = relationship("User", foreign_keys=[parent_id], backref="children_links")
    child = relationship("User", foreign_keys=[child_id], backref="parent_link")


class LearningGoal(Base):
    """
    Daily and weekly learning targets set by the parent for a child.
    The platform checks these and sends nudge notifications.
    """

    __tablename__ = "learning_goals"

    id = Column(Integer, primary_key=True, index=True)
    child_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    daily_minutes_target = Column(Integer, default=15)  # e.g. 15 minutes/day
    lessons_per_week = Column(Integer, default=3)  # e.g. 3 lessons/week
    max_daily_minutes = Column(Integer, default=30)  # screen time limit
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

    child = relationship("User", foreign_keys=[child_id], backref="learning_goal")


class ScreenTimeLog(Base):
    """
    Records each learning session for a child.
    Flutter sends session_end when the child leaves the app or
    the parent ends the session remotely.
    Used to enforce daily screen time limits.
    """

    __tablename__ = "screen_time_logs"

    id = Column(Integer, primary_key=True, index=True)
    child_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    session_start = Column(DateTime, nullable=False, default=func.now())
    session_end = Column(DateTime, nullable=True)  # null = currently active
    duration_mins = Column(Float, nullable=True)  # computed on session_end
    created_at = Column(DateTime, default=func.now())

    child = relationship("User", foreign_keys=[child_id], backref="screen_time_logs")


class WeeklyReport(Base):
    """
    AI-generated weekly progress report for a child.
    Generated every Monday by a background job and cached here.
    Parents can view it any time in the dashboard.

    The report contains:
      - summary_text: 3-4 sentence plain-English summary
      - phonemes_mastered: comma-separated list
      - phonemes_struggling: comma-separated list
      - avg_pronunciation_score: float
      - sessions_completed: int
      - total_minutes: int
      - recommended_focus: which phoneme to practise next
      - encouragement_message: personalised motivational message
    """

    __tablename__ = "weekly_reports"

    id = Column(Integer, primary_key=True, index=True)
    child_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    week_start = Column(DateTime, nullable=False)  # Monday 00:00 UTC
    summary_text = Column(Text, nullable=False)
    phonemes_mastered = Column(Text, nullable=True)  # JSON array string
    phonemes_struggling = Column(Text, nullable=True)  # JSON array string
    avg_pronunciation_score = Column(Float, nullable=True)
    sessions_completed = Column(Integer, default=0)
    total_minutes = Column(Float, default=0.0)
    recommended_focus = Column(String(100), nullable=True)
    encouragement_message = Column(Text, nullable=True)
    generated_at = Column(DateTime, default=func.now())

    child = relationship("User", foreign_keys=[child_id], backref="weekly_reports")
