"""add student profile fields: grade_level, school, city

Revision ID: 09af7253edbb
Revises: 566bb95187f4
Create Date: 2026-01-10 12:02:37.807525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09af7253edbb'
down_revision: Union[str, Sequence[str], None] = '566bb95187f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('school_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'grade_level')
    # ### end Alembic commands ###
