"""Add word_id FK to exercises

Revision ID: 5ec5086fee19
Revises: 55be59282c05
Create Date: 2025-11-11 08:39:31.739916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec5086fee19'
down_revision: Union[str, Sequence[str], None] = '55be59282c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('word_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercises', 'words', ['word_id'], ['id'])
    op.add_column('phonemes', sa.Column('word_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'phonemes', 'words', ['word_id'], ['id'])
    op.add_column('words', sa.Column('exercise_id', sa.Integer(), nullable=False))
    op.add_column('words', sa.Column('phoneme_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'words', 'phonemes', ['phoneme_id'], ['id'])
    op.create_foreign_key(None, 'words', 'exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'phoneme_id')
    op.drop_column('words', 'exercise_id')
    op.drop_constraint(None, 'phonemes', type_='foreignkey')
    op.drop_column('phonemes', 'word_id')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'word_id')
    # ### end Alembic commands ###
