"""Add lesson_id FK to phonemes

Revision ID: 8145870ccfb1
Revises: 43fa68405dbe
Create Date: 2025-11-11 09:24:24.697696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8145870ccfb1'
down_revision: Union[str, Sequence[str], None] = '43fa68405dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonemes', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'phonemes', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phonemes', type_='foreignkey')
    op.drop_column('phonemes', 'lesson_id')
    # ### end Alembic commands ###
