"""Added age column to users

Revision ID: d4be74d8ad6c
Revises: 8145870ccfb1
Create Date: 2025-11-18 10:32:10.658613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4be74d8ad6c'
down_revision: Union[str, Sequence[str], None] = '8145870ccfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.add_column('words', sa.Column('phonetic', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'words', ['text'])
    op.drop_column('words', 'phonitc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('phonitc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'words', type_='unique')
    op.drop_column('words', 'phonetic')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
