"""Add phonics models

Revision ID: 1699e0f311cc
Revises: 17d17e590670
Create Date: 2025-11-10 23:43:26.794131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1699e0f311cc'
down_revision: Union[str, Sequence[str], None] = '17d17e590670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('consonant', 'vowel', name='phoneme_type'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phonemes_id'), 'phonemes', ['id'], unique=False)
    op.create_index(op.f('ix_phonemes_symbol'), 'phonemes', ['symbol'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('LEVEL1', 'LEVEL2', 'LEVEL3', 'LEVEL4', 'LEVEL5', name='level'), nullable=True),
    sa.Column('phonitc', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_table('challenges')
    op.add_column('exercises', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.alter_column('exercises', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'type',
               existing_type=postgresql.ENUM('WORD', 'SENTENCE', 'PHONEME', name='exercisetype'),
               nullable=True)
    op.add_column('gamification', sa.Column('name', sa.String(), nullable=False))
    op.add_column('gamification', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('gamification', sa.Column('points_required', sa.Integer(), nullable=True))
    op.add_column('gamification', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('gamification_user_id_fkey'), 'gamification', type_='foreignkey')
    op.drop_column('gamification', 'streak')
    op.drop_column('gamification', 'user_id')
    op.drop_column('gamification', 'xp')
    op.drop_column('gamification', 'last_active')
    op.drop_column('gamification', 'badges')
    op.add_column('lessons', sa.Column('level', sa.Enum('LEVEL1', 'LEVEL2', 'LEVEL3', 'LEVEL4', 'LEVEL5', name='level'), nullable=False))
    op.add_column('lessons', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('lessons', 'description')
    op.drop_column('lessons', 'title')
    op.add_column('progress', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.add_column('progress', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('progress', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('progress', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('progress', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progress', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'progress', 'exercises', ['exercise_id'], ['id'])
    op.drop_column('progress', 'completed_at')
    op.drop_column('progress', 'completed_exercises')
    op.drop_column('progress', 'total_exercises')
    op.add_column('pronunciation_scores', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('pronunciation_scores', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('pronunciation_scores', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pronunciation_scores', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pronunciation_scores', 'feedback')
    op.drop_column('pronunciation_scores', 'created_at')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('age_group', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'age_group')
    op.drop_column('users', 'name')
    op.add_column('pronunciation_scores', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('pronunciation_scores', sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('pronunciation_scores', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pronunciation_scores', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pronunciation_scores', 'timestamp')
    op.drop_column('pronunciation_scores', 'audio_url')
    op.add_column('progress', sa.Column('total_exercises', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('progress', sa.Column('completed_exercises', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('progress', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.alter_column('progress', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('progress', 'updated_at')
    op.drop_column('progress', 'attempts')
    op.drop_column('progress', 'score')
    op.drop_column('progress', 'completed')
    op.drop_column('progress', 'exercise_id')
    op.add_column('lessons', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'created_at')
    op.drop_column('lessons', 'level')
    op.add_column('gamification', sa.Column('badges', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gamification', sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('gamification', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamification', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamification', sa.Column('streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('gamification_user_id_fkey'), 'gamification', 'users', ['user_id'], ['id'])
    op.drop_column('gamification', 'image_url')
    op.drop_column('gamification', 'points_required')
    op.drop_column('gamification', 'description')
    op.drop_column('gamification', 'name')
    op.alter_column('exercises', 'type',
               existing_type=postgresql.ENUM('WORD', 'SENTENCE', 'PHONEME', name='exercisetype'),
               nullable=False)
    op.alter_column('exercises', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('exercises', 'difficulty')
    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('challenges_pkey'))
    )
    op.create_table('friends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('friends_friend_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('friends_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('friends_pkey'))
    )
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_phonemes_symbol'), table_name='phonemes')
    op.drop_index(op.f('ix_phonemes_id'), table_name='phonemes')
    op.drop_table('phonemes')
    # ### end Alembic commands ###
