"""add_unique_constraint_progress_user_exercise

Revision ID: 3216f44b725d
Revises: 8de14b887107
Create Date: 2026-07-07 20:28:53.950563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3216f44b725d'
down_revision: Union[str, Sequence[str], None] = '8de14b887107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_progress_user_exercise', 'progress', ['user_id', 'exercise_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_progress_user_exercise', 'progress', type_='unique')
    # ### end Alembic commands ###
