"""recognition attempts

Revision ID: 48c6ce898b94
Revises: c1a96781b592
Create Date: 2026-07-31 20:32:55.125723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c6ce898b94'
down_revision: Union[str, Sequence[str], None] = 'c1a96781b592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recognition_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('phoneme_id', sa.Integer(), nullable=False),
    sa.Column('chosen_phoneme_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('explore', 'choose', name='recognitionmode'), nullable=False),
    sa.Column('option_count', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chosen_phoneme_id'], ['phonemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phoneme_id'], ['phonemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognition_attempts_answered_at'), 'recognition_attempts', ['answered_at'], unique=False)
    op.create_index(op.f('ix_recognition_attempts_child_id'), 'recognition_attempts', ['child_id'], unique=False)
    op.create_index(op.f('ix_recognition_attempts_id'), 'recognition_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_recognition_attempts_phoneme_id'), 'recognition_attempts', ['phoneme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_attempts_phoneme_id'), table_name='recognition_attempts')
    op.drop_index(op.f('ix_recognition_attempts_id'), table_name='recognition_attempts')
    op.drop_index(op.f('ix_recognition_attempts_child_id'), table_name='recognition_attempts')
    op.drop_index(op.f('ix_recognition_attempts_answered_at'), table_name='recognition_attempts')
    op.drop_table('recognition_attempts')
    # ### end Alembic commands ###

    # Autogenerate does not emit this; the type outlives the table it was
    # created for and blocks the next upgrade. Same reason as questslot in
    # c1a96781b592.
    sa.Enum(name='recognitionmode').drop(op.get_bind(), checkfirst=True)
