"""weekly promises

Revision ID: 4a5eb442dc7c
Revises: c68667de900a
Create Date: 2026-08-02 10:25:41.165033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5eb442dc7c'
down_revision: Union[str, Sequence[str], None] = 'c68667de900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_promises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('voice_url', sa.String(length=255), nullable=True),
    sa.Column('voice_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'week_start', name='uq_promise_child_week')
    )
    op.create_index(op.f('ix_weekly_promises_child_id'), 'weekly_promises', ['child_id'], unique=False)
    op.create_index(op.f('ix_weekly_promises_id'), 'weekly_promises', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_promises_week_start'), 'weekly_promises', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_promises_week_start'), table_name='weekly_promises')
    op.drop_index(op.f('ix_weekly_promises_id'), table_name='weekly_promises')
    op.drop_index(op.f('ix_weekly_promises_child_id'), table_name='weekly_promises')
    op.drop_table('weekly_promises')
    # ### end Alembic commands ###
