"""consolidated_initial_schema

Revision ID: 8de14b887107
Revises: 
Create Date: 2026-07-07 20:25:41.050831

This replaces the old migration history (previously 16 files, with two
disconnected chain heads - a broken state that would have made `alembic
upgrade head` fail with "Multiple head revisions are present"). The old
files also created several tables with no corresponding model in the
codebase anymore (friend_requests, friends, gamification, subscriptions,
user_achievements, teacher/student associations, and a stray
parent_children table from an unused duplicate model) - none of that is
recreated here.

This single migration creates exactly the tables that
app/models/__init__.py currently registers, autogenerated directly from
those models and verified against both SQLite and rendered Postgres DDL.

The old files are preserved for reference (not run by Alembic) in
alembic/versions_archive_old/.

IMPORTANT: if you already have a database that ran any of the old
migrations, do not run this against it directly - either start from a
fresh database, or reconcile manually. This is intended as a clean
starting point for a database with no migration history yet.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de14b887107'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('LEVEL1', 'LEVEL2', 'LEVEL3', 'LEVEL4', 'LEVEL5', name='level'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', 'parent', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('biometric_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_biometric_tokens_id'), 'biometric_tokens', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('WORD', 'SENTENCE', 'PHONEME', 'PARAGRAPH', name='exercisetype'), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_table('invite_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invite_links_id'), 'invite_links', ['id'], unique=False)
    op.create_table('learning_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('daily_minutes_target', sa.Integer(), nullable=True),
    sa.Column('lessons_per_week', sa.Integer(), nullable=True),
    sa.Column('max_daily_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index(op.f('ix_learning_goals_id'), 'learning_goals', ['id'], unique=False)
    op.create_table('parent_child_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index(op.f('ix_parent_child_links_id'), 'parent_child_links', ['id'], unique=False)
    op.create_table('phonemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ALPHABET', 'LONG_VOWEL', 'SHORT_VOWEL', 'DIPHTHONG', 'CONSONANT_BLEND', 'LETTER_COMBINATION', 'R_CONTROLLED_VOWEL', 'SILENT_LETTER', 'SCHWA', 'SUFFIX', name='phonemetype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phonemes_id'), 'phonemes', ['id'], unique=False)
    op.create_index(op.f('ix_phonemes_lesson_id'), 'phonemes', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_phonemes_symbol'), 'phonemes', ['symbol'], unique=True)
    op.create_table('screen_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('duration_mins', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screen_time_logs_id'), 'screen_time_logs', ['id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('phonemes_mastered', sa.Text(), nullable=True),
    sa.Column('phonemes_struggling', sa.Text(), nullable=True),
    sa.Column('avg_pronunciation_score', sa.Float(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('total_minutes', sa.Float(), nullable=True),
    sa.Column('recommended_focus', sa.String(length=100), nullable=True),
    sa.Column('encouragement_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    op.create_table('exercise_phoneme',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('phoneme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['phoneme_id'], ['phonemes.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'phoneme_id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_exercise_id'), 'progress', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    op.create_index(op.f('ix_progress_lesson_id'), 'progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    op.create_table('pronunciation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phoneme_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['phoneme_id'], ['phonemes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_scores_exercise_id'), 'pronunciation_scores', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_scores_id'), 'pronunciation_scores', ['id'], unique=False)
    op.create_index(op.f('ix_pronunciation_scores_phoneme_id'), 'pronunciation_scores', ['phoneme_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_scores_user_id'), 'pronunciation_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_scores_user_id'), table_name='pronunciation_scores')
    op.drop_index(op.f('ix_pronunciation_scores_phoneme_id'), table_name='pronunciation_scores')
    op.drop_index(op.f('ix_pronunciation_scores_id'), table_name='pronunciation_scores')
    op.drop_index(op.f('ix_pronunciation_scores_exercise_id'), table_name='pronunciation_scores')
    op.drop_table('pronunciation_scores')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_lesson_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_exercise_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_table('exercise_phoneme')
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_screen_time_logs_id'), table_name='screen_time_logs')
    op.drop_table('screen_time_logs')
    op.drop_index(op.f('ix_phonemes_symbol'), table_name='phonemes')
    op.drop_index(op.f('ix_phonemes_lesson_id'), table_name='phonemes')
    op.drop_index(op.f('ix_phonemes_id'), table_name='phonemes')
    op.drop_table('phonemes')
    op.drop_index(op.f('ix_parent_child_links_id'), table_name='parent_child_links')
    op.drop_table('parent_child_links')
    op.drop_index(op.f('ix_learning_goals_id'), table_name='learning_goals')
    op.drop_table('learning_goals')
    op.drop_index(op.f('ix_invite_links_id'), table_name='invite_links')
    op.drop_table('invite_links')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_biometric_tokens_id'), table_name='biometric_tokens')
    op.drop_table('biometric_tokens')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
