"""Fix model relationships and typos

Revision ID: a8518ecbb882
Revises: 5ec5086fee19
Create Date: 2025-11-11 09:04:50.277020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8518ecbb882'
down_revision: Union[str, Sequence[str], None] = '5ec5086fee19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('phonemes_word_id_fkey'), 'phonemes', type_='foreignkey')
    op.drop_column('phonemes', 'word_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonemes', sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('phonemes_word_id_fkey'), 'phonemes', 'words', ['word_id'], ['id'])
    op.alter_column('exercises', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
