"""engagement: daily quests, phoneme unlocks, streak freezes

Revision ID: c1a96781b592
Revises: 3216f44b725d
Create Date: 2026-07-31 18:44:13.266282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a96781b592'
down_revision: Union[str, Sequence[str], None] = '3216f44b725d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The spellings a phoneme licenses, comma-separated.
    #
    # Decodability was previously inferred from the symbol string, which
    # only works when the symbol happens to be a letter name. Half this
    # curriculum stores sounds as IPA — /ɪ/, /ɒ/ɔ/, /ʌ/ə/, /kw/, /ks/ —
    # so after teaching the entire alphabet the letters i, o, u, q and x
    # were still not decodable, and no word containing them could be
    # generated or shown. Nullable, so a phoneme with nothing set falls
    # back to the old inference and nothing that worked stops working.
    op.add_column('phonemes', sa.Column('graphemes', sa.String(), nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('quest_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'quest_date', name='uq_daily_quest_child_date')
    )
    op.create_index(op.f('ix_daily_quests_child_id'), 'daily_quests', ['child_id'], unique=False)
    op.create_index(op.f('ix_daily_quests_id'), 'daily_quests', ['id'], unique=False)
    op.create_index(op.f('ix_daily_quests_quest_date'), 'daily_quests', ['quest_date'], unique=False)
    op.create_table('streak_freezes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('earned_week_start', sa.Date(), nullable=False),
    sa.Column('consumed_for_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'earned_week_start', name='uq_freeze_child_week')
    )
    op.create_index(op.f('ix_streak_freezes_child_id'), 'streak_freezes', ['child_id'], unique=False)
    op.create_index(op.f('ix_streak_freezes_consumed_for_date'), 'streak_freezes', ['consumed_for_date'], unique=False)
    op.create_index(op.f('ix_streak_freezes_id'), 'streak_freezes', ['id'], unique=False)
    op.create_table('daily_quest_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Enum('review', 'current', 'stretch', name='questslot'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['daily_quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'slot', name='uq_quest_item_slot')
    )
    op.create_index(op.f('ix_daily_quest_items_id'), 'daily_quest_items', ['id'], unique=False)
    op.create_index(op.f('ix_daily_quest_items_quest_id'), 'daily_quest_items', ['quest_id'], unique=False)
    op.create_table('phoneme_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('phoneme_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phoneme_id'], ['phonemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'phoneme_id', name='uq_unlock_child_phoneme')
    )
    op.create_index(op.f('ix_phoneme_unlocks_child_id'), 'phoneme_unlocks', ['child_id'], unique=False)
    op.create_index(op.f('ix_phoneme_unlocks_id'), 'phoneme_unlocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phoneme_unlocks_id'), table_name='phoneme_unlocks')
    op.drop_index(op.f('ix_phoneme_unlocks_child_id'), table_name='phoneme_unlocks')
    op.drop_table('phoneme_unlocks')
    op.drop_index(op.f('ix_daily_quest_items_quest_id'), table_name='daily_quest_items')
    op.drop_index(op.f('ix_daily_quest_items_id'), table_name='daily_quest_items')
    op.drop_table('daily_quest_items')
    op.drop_index(op.f('ix_streak_freezes_id'), table_name='streak_freezes')
    op.drop_index(op.f('ix_streak_freezes_consumed_for_date'), table_name='streak_freezes')
    op.drop_index(op.f('ix_streak_freezes_child_id'), table_name='streak_freezes')
    op.drop_table('streak_freezes')
    op.drop_index(op.f('ix_daily_quests_quest_date'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_id'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_child_id'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_column('phonemes', 'graphemes')
    # ### end Alembic commands ###

    # Autogenerate does not emit this. Postgres creates the enum type as a
    # side effect of create_table but dropping the table leaves the type
    # behind, so a downgrade followed by an upgrade fails with
    # `type "questslot" already exists` — the exact breakage that stranded
    # english_phonics_db on an unrunnable migration chain.
    sa.Enum(name='questslot').drop(op.get_bind(), checkfirst=True)
