"""weekly goals

Revision ID: c68667de900a
Revises: 48c6ce898b94
Create Date: 2026-08-01 15:35:05.360710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68667de900a'
down_revision: Union[str, Sequence[str], None] = '48c6ce898b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('days', 'sounds_found', 'sounds_mastered', name='goalkind'), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('chosen_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'week_start', name='uq_goal_child_week')
    )
    op.create_index(op.f('ix_weekly_goals_child_id'), 'weekly_goals', ['child_id'], unique=False)
    op.create_index(op.f('ix_weekly_goals_id'), 'weekly_goals', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_goals_week_start'), 'weekly_goals', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_goals_week_start'), table_name='weekly_goals')
    op.drop_index(op.f('ix_weekly_goals_id'), table_name='weekly_goals')
    op.drop_index(op.f('ix_weekly_goals_child_id'), table_name='weekly_goals')
    op.drop_table('weekly_goals')
    # ### end Alembic commands ###

    # Autogenerate does not emit this; the type outlives the table it was
    # created for and blocks the next upgrade. Same reason as questslot in
    # c1a96781b592 and recognitionmode in 48c6ce898b94.
    sa.Enum(name='goalkind').drop(op.get_bind(), checkfirst=True)
