"""learning cursor

Revision ID: d3e8f1c5c602
Revises: b7c3d91f204e
Create Date: 2026-08-06 14:43:07.464941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e8f1c5c602'
down_revision: Union[str, Sequence[str], None] = 'b7c3d91f204e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('phoneme_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', name='uq_cursor_child')
    )
    op.create_index(op.f('ix_learning_cursors_child_id'), 'learning_cursors', ['child_id'], unique=False)
    op.create_index(op.f('ix_learning_cursors_id'), 'learning_cursors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_cursors_id'), table_name='learning_cursors')
    op.drop_index(op.f('ix_learning_cursors_child_id'), table_name='learning_cursors')
    op.drop_table('learning_cursors')
    # ### end Alembic commands ###
